In [13]:
import pandas as pd
import numpy as np

In [29]:
data = pd.read_csv("2.Student_Mental_Stress_and_Coping_Mechanisms.csv")

In [17]:
data.head()

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use
0,802-17-3671,22,Female,2,9,2,12,2,1,1,3,5,9,No,1,Walking or Nature Walks,4,No,Yes,1
1,871-12-8572,25,Female,0,28,0,6,0,1,1,1,2,9,Yes,3,Meditation,2,Yes,No,1
2,495-13-2672,24,Female,0,45,3,12,10,3,3,1,4,9,Yes,5,Reading,1,Yes,Yes,3
3,365-77-2496,20,Male,2,8,7,7,4,1,3,2,5,1,No,1,Social Media Engagement,2,Yes,No,4
4,664-76-5622,28,Male,0,14,6,8,1,2,4,4,2,7,Yes,1,Exercise,1,Yes,No,3

In [18]:
data.describe()

,Age,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Diet_Quality,Cognitive_Distortions,Substance_Use
count,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000
mean,23.919737,1.996053,29.130263,4.234211,8.093421,4.934211,2.972368,3.021053,2.982895,2.963158,5.363158,3.042105,3.007895,2.996053
std,3.819392,1.416535,18.104662,2.565174,2.596838,3.082679,1.413477,1.452662,1.391096,1.369231,2.902856,1.453111,1.432703,1.385502
min,18.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,21.000000,1.000000,13.000000,2.000000,6.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000
50%,24.000000,2.000000,29.000000,4.000000,8.000000,5.000000,3.000000,3.000000,3.000000,3.000000,5.000000,3.000000,3.000000,3.000000
75%,27.000000,3.000000,45.000000,7.000000,10.000000,8.000000,4.000000,4.000000,4.000000,4.000000,8.000000,4.000000,4.000000,4.000000
max,30.000000,4.000000,60.000000,8.000000,12.000000,10.000000,5.000000,5.000000,5.000000,5.000000,10.000000,5.000000,5.000000,5.000000

In [20]:
data[['Age', 'Study_Hours_Per_Week', 'Mental_Stress_Level']].describe()

              Age  Study_Hours_Per_Week  Mental_Stress_Level
count  760.000000            760.000000           760.000000
mean    23.919737             29.130263             5.363158
std      3.819392             18.104662             2.902856
min     18.000000              0.000000             1.000000
25%     21.000000             13.000000             3.000000
50%     24.000000             29.000000             5.000000
75%     27.000000             45.000000             8.000000
max     30.000000             60.000000            10.000000

In [21]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Student_ID                          760 non-null    str
 1   Age                                 760 non-null    int64
 2   Gender                              760 non-null    str
 3   Academic_Performance_(GPA)          760 non-null    int64
 4   Study_Hours_Per_Week                760 non-null    int64
 5   Social_Media_Usage_(Hours_per_day)  760 non-null    int64
 6   Sleep_Duration_(Hours_per_night)    760 non-null    int64
 7   Physical_Exercise_(Hours_per_week)  760 non-null    int64
 8   Family_Support                      760 non-null    int64
 9   Financial_Stress                    760 non-null    int64
 10  Peer_Pressure                       760 non-null    int64
 11  Relationship_Stress                 760 non-null    int64
 12  Mental_Stress_Level                 760 non-null    int64
 13  Counseling_Attendance               760 non-null    str
 14  Diet_Quality                        760 non-null    int64
 15  Stress_Coping_Mechanisms            760 non-null    str
 16  Cognitive_Distortions               760 non-null    int64
 17  Family_Mental_Health_History        760 non-null    str
 18  Medical_Condition                   760 non-null    str
 19  Substance_Use                       760 non-null    int64
dtypes: int64(14), str(6)
memory usage: 118.9 KB

In [22]:
data.isnull()

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
756,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
757,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
758,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
759,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [23]:
data.isnull().sum()

Student_ID                            0
Age                                   0
Gender                                0
Academic_Performance_(GPA)            0
Study_Hours_Per_Week                  0
Social_Media_Usage_(Hours_per_day)    0
Sleep_Duration_(Hours_per_night)      0
Physical_Exercise_(Hours_per_week)    0
Family_Support                        0
Financial_Stress                      0
Peer_Pressure                         0
Relationship_Stress                   0
Mental_Stress_Level                   0
Counseling_Attendance                 0
Diet_Quality                          0
Stress_Coping_Mechanisms              0
Cognitive_Distortions                 0
Family_Mental_Health_History          0
Medical_Condition                     0
Substance_Use                         0
dtype: int64

In [24]:
data.loc[data['Age'] == 30]

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use
21,861-60-5151,30,Agender,0,37,4,12,10,4,3,5,4,4,No,2,Watching Sports,5,Yes,No,1
46,532-53-7106,30,Male,4,28,7,11,6,2,3,3,3,1,Yes,2,Watching Sports,5,Yes,No,3
62,683-65-1968,30,Male,3,0,1,6,9,5,3,4,1,9,No,5,Meditation,3,No,Yes,4
64,209-32-8628,30,Male,0,31,2,11,0,4,4,5,2,8,No,3,Spending Time Alone,3,No,Yes,1
67,800-36-7705,30,Female,0,14,3,10,3,1,4,5,1,5,No,3,Exercise,4,Yes,No,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,345-50-9214,30,Male,3,2,2,7,6,5,3,4,1,2,No,1,Watching Sports,4,No,Yes,3
744,626-36-8884,30,Female,0,41,4,7,2,3,2,2,2,4,Yes,1,Walking or Nature Walks,5,No,Yes,2
746,143-10-3794,30,Female,2,38,0,9,2,2,2,5,1,4,No,2,Travelling,1,Yes,Yes,3
747,386-97-0412,30,Male,4,17,0,6,2,5,2,3,3,4,Yes,3,Exercise,1,Yes,Yes,4
752,527-24-3188,30,Male,1,36,0,10,10,5,4,5,3,3,Yes,4,Yoga,1,No,No,1

In [30]:
data.loc[(data['Age'] == 30) & (data['Academic_Performance_(GPA)'] == 4) & (data['Gender'] == 'Male')]

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use
46,532-53-7106,30,Male,4,28,7,11,6,2,3,3,3,1,Yes,2,Watching Sports,5,Yes,No,3
91,631-57-6187,30,Male,4,42,2,7,5,3,3,4,4,8,Yes,5,Meditation,2,Yes,Yes,3
460,593-90-7730,30,Male,4,36,4,8,0,5,1,5,4,10,No,4,Spending Time Alone,3,Yes,Yes,5
486,757-52-0603,30,Male,4,8,6,4,7,5,5,1,4,3,Yes,4,Yoga,4,No,No,3
544,330-13-8536,30,Male,4,44,5,6,8,5,4,4,2,3,Yes,3,Reading,5,No,No,2
603,670-07-5476,30,Male,4,43,4,7,0,1,3,4,2,5,Yes,2,Travelling,3,Yes,Yes,2
747,386-97-0412,30,Male,4,17,0,6,2,5,2,3,3,4,Yes,3,Exercise,1,Yes,Yes,4

In [31]:
data.loc[(data['Age'] == 30) & (data['Academic_Performance_(GPA)'] == 4) & (data['Gender'] == 'Male')].head()

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use
46,532-53-7106,30,Male,4,28,7,11,6,2,3,3,3,1,Yes,2,Watching Sports,5,Yes,No,3
91,631-57-6187,30,Male,4,42,2,7,5,3,3,4,4,8,Yes,5,Meditation,2,Yes,Yes,3
460,593-90-7730,30,Male,4,36,4,8,0,5,1,5,4,10,No,4,Spending Time Alone,3,Yes,Yes,5
486,757-52-0603,30,Male,4,8,6,4,7,5,5,1,4,3,Yes,4,Yoga,4,No,No,3
544,330-13-8536,30,Male,4,44,5,6,8,5,4,4,2,3,Yes,3,Reading,5,No,No,2

In [35]:
data.iloc[100:110, 2:6]

,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day)
100,Male,3,8,4
101,Female,1,59,1
102,Male,2,54,4
103,Male,3,7,7
104,Female,4,57,8
105,Bigender,4,29,3
106,Female,2,3,7
107,Male,4,3,6
108,Female,2,36,4
109,Male,1,53,7

In [36]:
data.iloc[100:110, [2,6]]

       Gender  Sleep_Duration_(Hours_per_night)
100      Male                                 9
101    Female                                 7
102      Male                                10
103      Male                                 8
104    Female                                 5
105  Bigender                                12
106    Female                                 9
107      Male                                10
108    Female                                11
109      Male                                 9

In [41]:
data.loc[data['Age'].isnull()]

Empty DataFrame
Columns: [Student_ID, Age, Gender, Academic_Performance_(GPA), Study_Hours_Per_Week, Social_Media_Usage_(Hours_per_day), Sleep_Duration_(Hours_per_night), Physical_Exercise_(Hours_per_week), Family_Support, Financial_Stress, Peer_Pressure, Relationship_Stress, Mental_Stress_Level, Counseling_Attendance, Diet_Quality, Stress_Coping_Mechanisms, Cognitive_Distortions, Family_Mental_Health_History, Medical_Condition, Substance_Use]
Index: []

In [44]:
data['Academic_Performance_(GPA)'].value_counts()

Academic_Performance_(GPA)
3    170
0    161
2    149
4    143
1    137
Name: count, dtype: int64

In [45]:
data.sort_values('Academic_Performance_(GPA)')

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use
749,593-06-7718,25,Male,0,15,5,4,3,1,5,1,2,4,No,5,Walking or Nature Walks,3,No,Yes,4
1,871-12-8572,25,Female,0,28,0,6,0,1,1,1,2,9,Yes,3,Meditation,2,Yes,No,1
2,495-13-2672,24,Female,0,45,3,12,10,3,3,1,4,9,Yes,5,Reading,1,Yes,Yes,3
744,626-36-8884,30,Female,0,41,4,7,2,3,2,2,2,4,Yes,1,Walking or Nature Walks,5,No,Yes,2
4,664-76-5622,28,Male,0,14,6,8,1,2,4,4,2,7,Yes,1,Exercise,1,Yes,No,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,651-96-1453,20,Male,4,12,6,4,3,4,5,1,1,6,Yes,5,Yoga,1,Yes,Yes,2
24,589-36-1147,28,Male,4,58,8,11,4,3,5,3,1,3,Yes,5,Walking or Nature Walks,1,Yes,Yes,4
23,115-75-7195,28,Agender,4,21,8,12,8,4,2,3,5,1,Yes,1,Travelling,3,Yes,Yes,4
747,386-97-0412,30,Male,4,17,0,6,2,5,2,3,3,4,Yes,3,Exercise,1,Yes,Yes,4
754,836-77-4994,19,Male,4,7,6,7,8,2,1,1,3,5,Yes,2,Travelling,1,No,No,4

In [9]:
data2 = pd.read_csv("2.Student_Mental_Stress_and_Coping_Mechanisms.csv")

In [10]:
mcp = np.array(data2['Study_Hours_Per_Week'])
inc = mcp / 7
incr_col = pd.DataFrame(inc, columns=['Study_Hour_Per_Day'])
data2 = pd.concat([data2, incr_col], axis = 1)
data2.head()

,Student_ID,Age,Gender,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,...,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use,Study_Hour_Per_Day
0,802-17-3671,22,Female,2,9,2,12,2,1,1,...,5,9,No,1,Walking or Nature Walks,4,No,Yes,1,1.285714
1,871-12-8572,25,Female,0,28,0,6,0,1,1,...,2,9,Yes,3,Meditation,2,Yes,No,1,4.000000
2,495-13-2672,24,Female,0,45,3,12,10,3,3,...,4,9,Yes,5,Reading,1,Yes,Yes,3,6.428571
3,365-77-2496,20,Male,2,8,7,7,4,1,3,...,5,1,No,1,Social Media Engagement,2,Yes,No,4,1.142857
4,664-76-5622,28,Male,0,14,6,8,1,2,4,...,2,7,Yes,1,Exercise,1,Yes,No,3,2.000000

In [11]:
data2.drop(columns=['Study_Hours_Per_Week'])

,Student_ID,Age,Gender,Academic_Performance_(GPA),Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Stress_Coping_Mechanisms,Cognitive_Distortions,Family_Mental_Health_History,Medical_Condition,Substance_Use,Study_Hour_Per_Day
0,802-17-3671,22,Female,2,2,12,2,1,1,3,5,9,No,1,Walking or Nature Walks,4,No,Yes,1,1.285714
1,871-12-8572,25,Female,0,0,6,0,1,1,1,2,9,Yes,3,Meditation,2,Yes,No,1,4.000000
2,495-13-2672,24,Female,0,3,12,10,3,3,1,4,9,Yes,5,Reading,1,Yes,Yes,3,6.428571
3,365-77-2496,20,Male,2,7,7,4,1,3,2,5,1,No,1,Social Media Engagement,2,Yes,No,4,1.142857
4,664-76-5622,28,Male,0,6,8,1,2,4,4,2,7,Yes,1,Exercise,1,Yes,No,3,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,826-89-7993,24,Genderfluid,2,4,11,8,5,2,4,5,2,Yes,1,Exercise,3,Yes,No,2,7.142857
756,681-15-6754,23,Female,3,6,12,7,1,4,2,1,1,Yes,2,Meditation,4,Yes,No,1,0.714286
757,714-33-5373,23,Male,1,3,11,5,2,4,3,3,9,Yes,5,Social Media Engagement,4,Yes,No,3,2.428571
758,849-54-1252,29,Female,1,8,10,4,2,1,2,2,2,No,4,Meditation,4,No,Yes,3,2.142857
759,862-68-5364,21,Female,3,3,5,9,5,1,4,4,4,Yes,5,Reading,2,Yes,No,1,0.285714

In [15]:
data.groupby('Gender')['Academic_Performance_(GPA)'].unique().reset_index()

        Gender Academic_Performance_(GPA)
0      Agender            [0, 4, 1, 3, 2]
1     Bigender            [3, 2, 4, 1, 0]
2       Female            [2, 0, 1, 3, 4]
3  Genderfluid            [4, 1, 0, 3, 2]
4  Genderqueer               [1, 3, 2, 0]
5         Male            [2, 0, 3, 1, 4]
6   Non-binary               [4, 2, 1, 3]
7   Polygender               [3, 2, 0, 4]

In [16]:
data.groupby('Gender', as_index=False)['Academic_Performance_(GPA)'].median()

        Gender  Academic_Performance_(GPA)
0      Agender                         1.5
1     Bigender                         2.0
2       Female                         2.0
3  Genderfluid                         2.5
4  Genderqueer                         2.0
5         Male                         2.0
6   Non-binary                         2.5
7   Polygender                         2.5

In [24]:
data['Study_Hours_Per_Week'].unique()

array([ 9, 28, 45,  8, 14, 27, 30, 12, 19,  4, 38,  2, 39, 44, 49, 26, 54,
       35, 37, 21, 58, 32, 13, 46, 43,  7, 11, 34, 36, 40, 15,  6, 25, 59,
       17, 10,  5, 48, 60, 20,  0, 24, 18,  1, 31, 57, 53, 41, 50, 16, 42,
       51, 33, 47, 29,  3, 23, 55, 56, 22, 52])

In [30]:
data['Counseling_Attendance'] = pd.to_numeric(data['Counseling_Attendance'].str.replace('Yes', '1').str.replace('No', '0'))
data.dtypes

Student_ID                              str
Age                                   int64
Gender                                  str
Academic_Performance_(GPA)            int64
Study_Hours_Per_Week                  int64
Social_Media_Usage_(Hours_per_day)    int64
Sleep_Duration_(Hours_per_night)      int64
Physical_Exercise_(Hours_per_week)    int64
Family_Support                        int64
Financial_Stress                      int64
Peer_Pressure                         int64
Relationship_Stress                   int64
Mental_Stress_Level                   int64
Counseling_Attendance                 int64
Diet_Quality                          int64
Stress_Coping_Mechanisms                str
Cognitive_Distortions                 int64
Family_Mental_Health_History            str
Medical_Condition                       str
Substance_Use                         int64
dtype: object

In [32]:
data.corr(numeric_only=True)

,Age,Academic_Performance_(GPA),Study_Hours_Per_Week,Social_Media_Usage_(Hours_per_day),Sleep_Duration_(Hours_per_night),Physical_Exercise_(Hours_per_week),Family_Support,Financial_Stress,Peer_Pressure,Relationship_Stress,Mental_Stress_Level,Counseling_Attendance,Diet_Quality,Cognitive_Distortions,Substance_Use
Age,1.000000,0.001159,0.023549,-0.002382,0.036756,-0.032789,-0.003340,-0.004682,0.059751,-0.005101,-0.048228,0.053055,-0.004613,0.030453,-0.003795
Academic_Performance_(GPA),0.001159,1.000000,-0.000237,0.033613,-0.017450,0.035845,0.001262,0.050622,0.018018,0.014869,-0.036178,0.045501,-0.016561,0.009753,0.015432
Study_Hours_Per_Week,0.023549,-0.000237,1.000000,0.002775,-0.024219,-0.013066,-0.008097,-0.014983,-0.039512,-0.021278,-0.080521,0.042684,-0.020541,-0.041132,-0.027502
Social_Media_Usage_(Hours_per_day),-0.002382,0.033613,0.002775,1.000000,0.026577,0.057434,-0.004390,0.049236,-0.026567,-0.045930,0.011564,0.010924,-0.003003,0.049327,-0.087968
Sleep_Duration_(Hours_per_night),0.036756,-0.017450,-0.024219,0.026577,1.000000,-0.022108,0.000704,-0.012746,-0.032746,-0.004218,0.068027,-0.034327,-0.009074,-0.015780,0.023173
Physical_Exercise_(Hours_per_week),-0.032789,0.035845,-0.013066,0.057434,-0.022108,1.000000,0.003513,0.052974,0.018171,0.018154,-0.066084,0.048306,-0.029970,0.010857,0.024926
Family_Support,-0.003340,0.001262,-0.008097,-0.004390,0.000704,0.003513,1.000000,0.028517,0.108979,-0.016865,0.008871,0.045291,-0.016752,0.023529,-0.010820
Financial_Stress,-0.004682,0.050622,-0.014983,0.049236,-0.012746,0.052974,0.028517,1.000000,-0.013513,-0.033392,0.025367,-0.037807,-0.027259,-0.015273,-0.042509
Peer_Pressure,0.059751,0.018018,-0.039512,-0.026567,-0.032746,0.018171,0.108979,-0.013513,1.000000,-0.073653,-0.058167,0.031013,-0.004857,0.031799,0.018422
Relationship_Stress,-0.005101,0.014869,-0.021278,-0.045930,-0.004218,0.018154,-0.016865,-0.033392,-0.073653,1.000000,-0.086460,-0.060126,-0.083980,0.016267,-0.012578
Mental_Stress_Level,-0.048228,-0.036178,-0.080521,0.011564,0.068027,-0.066084,0.008871,0.025367,-0.058167,-0.086460,1.000000,-0.049410,0.007927,-0.031419,-0.023229
Counseling_Attendance,0.053055,0.045501,0.042684,0.010924,-0.034327,0.048306,0.045291,-0.037807,0.031013,-0.060126,-0.049410,1.000000,0.016847,-0.045856,0.050322
Diet_Quality,-0.004613,-0.016561,-0.020541,-0.003003,-0.009074,-0.029970,-0.016752,-0.027259,-0.004857,-0.083980,0.007927,0.016847,1.000000,0.027053,-0.052270
Cognitive_Distortions,0.030453,0.009753,-0.041132,0.049327,-0.015780,0.010857,0.023529,-0.015273,0.031799,0.016267,-0.031419,-0.045856,0.027053,1.000000,-0.015914
Substance_Use,-0.003795,0.015432,-0.027502,-0.087968,0.023173,0.024926,-0.010820,-0.042509,0.018422,-0.012578,-0.023229,0.050322,-0.052270,-0.015914,1.000000